name: null
favicon: null
layout_spectrum: 0.6952961715869606
typography_spectrum: 0.9714369997382164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.06736740213818848
  lightness: 0.999386950628832
  saturation: 0.209680687636137
  rhythmicContrast: 0.9698572312481701
purpose: []
